AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS + Redis simple setup for default VPC'

Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String

Resources:
  MyAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for RDS and Redis'
      VpcId: !Ref AWS::NoValue
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  MyAppDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: myappdb
      PubliclyAccessible: true
      BackupRetentionPeriod: 1
      VPCSecurityGroups:
        - !Ref MyAppSecurityGroup

  MyAppRedis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheNodes: 1
      ClusterName: myapp-cache
      VpcSecurityGroupIds:
        - !Ref MyAppSecurityGroup
      PreferredAvailabilityZone: ap-southeast-1a

Outputs:
  RdsEndpoint:
    Value: !GetAtt MyAppDB.Endpoint.Address
  RedisEndpoint:
    Value: !GetAtt MyAppRedis.RedisEndpoint.Address
